### ISSUE TITLE
How do you create the gImage_alberteinstein data?

### ISSUE THREAD

**Issue by MichaelBitard** [paperdink/minimal_GxEPD#1]
Hi, thanks for this neat project.

I'm currently playing with my paperdink and I'd like to know how did you generage the char array representing albert enstein. I assume it comes from an image at some point and I'd like to do something similar.

**Comment by rgujju** [comment]
You can use the Image2LCD tool from good-display.
Set scan mode: Horizontal scan, BitsPixel: monochrome and max width: 400 max height 300.

**Comment by MichaelBitard** [comment]
Thanks a lot!
